### PR TITLE
better woocommerce detection (previous one doesn't work multisite)

### PR DESCRIPTION
**Pull request by vicocotea**
found the solution here : 
https://wp-buddy.com/blog/check-wordpress-plugin-sitewide-active-network-active/

### CODE REVIEW

**Comment by Mte90** [comment]
Thank you for the improvement!

**Comment by vicocotea** [comment]
Hi @Mte90 

I have another issue, I can't submit form in the setting page.
The issue seems to be related to the mailchimp form.
When I remove all the form from mailchimp it works.

I don't really know how to debug it, expect that the mailchimp form is inside the woocommerce form, wired !?

**Comment by Mte90** [comment]
Uhm as I can see now after testing the `is_plugin_active` exist only on admin and require an hook to be executed so it is not the best option.
For your problem can you open a new ticket?

**Comment by vicocotea** [comment]
Yes sorry for `is_plugin_active` I tested it locally but it doesn't work online.
And yes for the other ticket.

**Comment by Mte90** [comment]
I already fixed for the is_plugin_active :-) now use the code inside the function without use the official one.

**Pull request merged**
